### ISSUE TITLE
Een INP moet meer ouders kunnen hebben

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#35]
# Impediment

Specificatie op dit moment kan maximaal 1 "ouders" aan van een INP, als object i.p.v. een lijst van ouders.

https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/api-specificatie/BRPB1.0.yaml#L910
```yaml
        ouders:
          type: "object"
          description: "De ingezetene, zijnde de ouder, waarnaar de KIND-OUDER-RELATIE\
            \ verwijst"
          properties:
            href:
              type: "string"
              format: "uri"
```
