### ISSUE TITLE
Typo in Verblijfstitel_tabel.datumEindeGeldigheidVerblijfstiel

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#37]
# Impediment

https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/api-specificatie/BRPB1.0.yaml#L683
```yaml
        datumEindeGeldigheidVerblijfstiel:
          type: "string"
          title: "Datum einde geldigheid verblijfstiel"
          description: "Einde geldigheid van de verblijfstitel"
```

"[...] tiel" moet "titel" zijn.
